### ISSUE TITLE
Error: reading PAT token from keyring failed: Failed to activate service 'org.freedesktop.secrets': timed out (service_start_timeout=120000ms)

### ISSUE THREAD

**Issue by sylvaindethier** [anchordotdev/cli#13]
**Are there any additional details you would like to share?**

---

**Command:** `config`
**Version:** `0.0.28 (linux/amd64) Commit: e4ca5ed3db8d57f2f8dab6d1d830e2beb75caf68 BuildDate: 2024-04-30T13:53:03Z`
**Arguments:** `[]`
**Flags:** `[]`
**Stdout:**
```
─── Client ─────────────────────────────────────────────────────────────────────
    * Checking authentication: probing credentials locally…[38;5;57m⠋[0m
```

**Comment by geemus** [comment]
@sylvaindethier Is this still an issue for you, or is it a duplicate of #12?

**Comment by sylvaindethier** [comment]
Still an issue, still timeout (service_start_timeout=120000ms)

**Comment by sylvaindethier** [comment]
@geemus Still an issue, same error (service_start_timeout=120000ms)

**Comment by benburkert** [comment]
@sylvaindethier can you try running `gnome-keyring-daemon --daemonize --replace`? If that fixes it, it may be an issue with the gnome-keyring system service configuration.

**Comment by sylvaindethier** [comment]
@benburkert  i've run 1st `gnome-keyring-daemon --daemonize --replace`, it output:
```
 gnome-keyring-daemon --daemonize --replace
** Message: 20:19:32.760: Replacing daemon, using directory: /mnt/wslg/runtime-dir/keyring
GNOME_KEYRING_CONTROL=/mnt/wslg/runtime-dir/keyring
SSH_AUTH_SOCK=/mnt/wslg/runtime-dir/keyring/ssh
```

Then i've re run `anchor lcl config`, it outputs:
```
anchor lcl config
    * Checking authentication: probing credentials locally…⠦
# Error! reading PAT token from keyring failed: Failed to activate service 'org.freedesktop.secrets': timed out (service_start_timeout=120000ms) `config`
    | We are sorry you encountered this error.
    ! Press Enter to open an issue on Github.
```

I didn't submit the issue.

By the way I was just trying the tool to get https on my localhost. This is not for work, so for the moment i don't mind.
Tell me if you really want to fix this issue.

**Comment by benburkert** [comment]
@sylvaindethier we just released `v0.0.30`, which should have better support for headless linux environments like WSL. There are still a few known issues that we're working through which we expect will impact you, i'll update this issue when those have been sorted.

**Comment by sylvaindethier** [comment]
@benburkert  i've upgraded to 0.30.0, and yes indeed i do have the same issue, see #14

**Comment by sylvaindethier** [comment]
v0.31.0 fixes the issue (with or without `gnome-keyring`)
Thanks !
