### ISSUE TITLE
Error: unexpected 400 status response: Invalid domain: social-app_backend.lcl.host

### ISSUE THREAD

**Issue by sylvaindethier** [anchordotdev/cli#15]
**Are there any additional details you would like to share?**

---

**Command:** `setup`
**Version:** `0.0.31 (linux/amd64) Commit: 6573afe276a940457712d5c6fb0d5d09af1f002a BuildDate: 2024-05-03T20:12:14Z`
**Arguments:** `[]`
**Flags:** `[]`
**Stdout:**
```
[1m# Signin to Anchor.dev [2m`anchor auth signin`[0m[0m
[2m    | Please sign up or sign in with your Anchor account.[0m
    - Copied your user code [1mSFQB-WJKX[0m to your clipboard.
    - Opened [4;2;4mh[0m[4;2;4mt[0m[4;2;4mt[0m[4;2;4mp[0m[4;2;4ms[0m[4;2;4m:[0m[4;2;4m/[0m[4;2;4m/[0m[4;2;4ma[0m[4;2;4mn[0m[4;2;4mc[0m[4;2;4mh[0m[4;2;4mo[0m[4;2;4mr[0m[4;2;4m.[0m[4;2;4md[0m[4;2;4me[0m[4;2;4mv[0m[4;2;4m/[0m[4;2;4mu[0m[4;2;4ms[0m[4;2;4me[0m[4;2;4mr[0m[4;2;4ms[0m[4;2;4m/[0m[4;2;4ms[0m[4;2;4mi[0m[4;2;4mg[0m[4;2;4mn[0m[4;2;4m_[0m[4;2;4mi[0m[4;2;4mn[0m[4;2;4m/[0m[4;2;4mc[0m[4;2;4ml[0m[4;2;4mi[0m[4;2;4m?[0m[4;2;4ms[0m[4;2;4mi[0m[4;2;4mg[0m[4;2;4mn[0m[4;2;4mu[0m[4;2;4mp[0m[4;2;4m_[0m[4;2;4ms[0m[4;2;4mr[0m[4;2;4mc[0m[4;2;4m=[0m[4;2;4ml[0m[4;2;4mc[0m[4;2;4ml[0m[4;2;4mh[0m[4;2;4mo[0m[4;2;4ms[0m[4;2;4mt[0m in your browser
    * Signing in… [38;5;61m⠋[0m
[1m[48;5;229m[38;5;232m![0m[0m[38;5;229m Warning:[0m Unable to access keyring, credentials will not be stored.[0m
[1m# Setup lcl.host Application [2m`anchor lcl setup`[0m[0m
[2m    | We'll start by scanning your current directory, then ask you questions about[0m
[2m    | your local application so that we can generate setup instructions for you.[0m
    - Scanned current directory.
    - Entered [1mjavascript[0m application server type
    - Entered [1msocial-app_backend[0m application name.
    - Entered [1msocial-app_backend.lcl.host[0m domain for local application development
    - Resolved [4;2;4ms[0m[4;2;4mo[0m[4;2;4mc[0m[4;2;4mi[0m[4;2;4ma[0m[4;2;4ml[0m[4;2;4m-[0m[4;2;4ma[0m[4;2;4mp[0m[4;2;4mp[0m[4;2;4m_[0m[4;2;4mb[0m[4;2;4ma[0m[4;2;4mc[0m[4;2;4mk[0m[4;2;4me[0m[4;2;4mn[0m[4;2;4md[0m[4;2;4m.[0m[4;2;4ml[0m[4;2;4mc[0m[4;2;4ml[0m[4;2;4m.[0m[4;2;4mh[0m[4;2;4mo[0m[4;2;4ms[0m[4;2;4mt[0m domain: success!
[2m    | Now we'll provision your application's resources on Anchor.dev and the HTTPS[0m
[2m    | certificates for your development environment.[0m
    - Creating [1msocial-app_backend[0m [[4;2;4ms[0m[4;2;4mo[0m[4;2;4mc[0m[4;2;4mi[0m[4;2;4ma[0m[4;2;4ml[0m[4;2;4m-[0m[4;2;4ma[0m[4;2;4mp[0m[4;2;4mp[0m[4;2;4m_[0m[4;2;4mb[0m[4;2;4ma[0m[4;2;4mc[0m[4;2;4mk[0m[4;2;4me[0m[4;2;4mn[0m[4;2;4md[0m[4;2;4m.[0m[4;2;4ml[0m[4;2;4mc[0m[4;2;4ml[0m[4;2;4m.[0m[4;2;4mh[0m[4;2;4mo[0m[4;2;4ms[0m[4;2;4mt[0m, [4;2;4ms[0m[4;2;4mo[0m[4;2;4mc[0m[4;2;4mi[0m[4;2;4ma[0m[4;2;4ml[0m[4;2;4m-[0m[4;2;4ma[0m[4;2;4mp[0m[4;2;4mp[0m[4;2;4m_[0m[4;2;4mb[0m[4;2;4ma[0m[4;2;4mc[0m[4;2;4mk[0m[4;2;4me[0m[4;2;4mn[0m[4;2;4md[0m[4;2;4m.[0m[4;2;4ml[0m[4;2;4mo[0m[4;2;4mc[0m[4;2;4ma[0m[4;2;4ml[0m[4;2;4mh[0m[4;2;4mo[0m[4;2;4ms[0m[4;2;4mt[0m] javascript resources on Anchor.dev… [38;5;61m⠋[0m
```

**Comment by geemus** [comment]
Hey, sorry you hit another bug here.

The underscore character is not allowed in domain names, which is what the error indicates. In the flow when it prompts you to enter a domain name, it should prevent you from entering underscores. But underscores are allowed in app names, and by default we set the domain name to the app name, which would let this slip through the validation. It is an edge case we had overlooked, unfortunately.

If you use a domain name that is valid, this should work, and I'll work on a fix for the edge case I've just described and update when we have something.

Thanks again for sharing the reports and your patience and we continue to refine things.

**Comment by benburkert** [comment]
@sylvaindethier we just released `v0.0.32` which fixes the subdomain name generator that @geemus mentioned, please let us know if you're still having issues or this is behaving in an unexpected way.

**Comment by sylvaindethier** [comment]
@geemus @benburkert i've upgraded to v0.0.32. Now it works fine. But as suggested by @geemus i did not use a subdomain with an underscore in its name.

I still have a requested. When i tried to setup with `social-app_backend` it did not work, and i have a 500 error when i try to edit it. I just want to delete it. Can you guys do it please ?

**Comment by sylvaindethier** [comment]
After `anchor lcl setup`, I've strictly follow the instruction guide, and tried to establish a connection, but it failed.

```js
// index.js

const { createSNICallback } = require("anchor-pki/auto-cert/sni-callback");
const {
  TermsOfServiceAcceptor,
} = require("anchor-pki/auto-cert/terms-of-service-acceptor");
const https = require("node:https");

process.env.ACME_DIRECTORY_URL =
  "https://anchor.dev/sylvaindethier/localhost/x509/ca/acme";
process.env.ACME_CONTACT = "dethiersylvain@gmail.com+${ACME_KID}";
process.env.ACME_ALLOW_IDENTIFIERS =
  "swc-backend.lcl.host,swc-backend.localhost";
process.env.HTTPS_PORT = "44322";

console.log(process.env);
const SNICallback = createSNICallback({
  name: "sni-callback",
  tosAcceptors: TermsOfServiceAcceptor.createAny(),
  cacheDir: "tmp/acme",

  // The following are defaults
  //
  // directoryUrl: process.env.ACME_DIRECTORY_URL,
  // contact: process.env.ACME_CONTACT,
  // externalAccountBinding: {
  //   kid: process.env.ACME_KID,
  //   hmacKey: process.env.ACME_HMAC_KEY
  // },
});

console.log("HTTPS_PORT", process.env.HTTPS_PORT);
https
  .createServer({ SNICallback }, (req, res) => {
    res.writeHead(200);
    res.end("hello world\n");
  })
  .listen(process.env.HTTPS_PORT);
```

`tmp/acme` directory and the three `swc-backend.lcl.host+1-cert.pem`, `swc-backend.lcl.host+1-chain.pem`, `swc-backend.lcl.host+1-key.pem` files were created.

So I don't know what I'm missing or doing wrong.

**Comment by sylvaindethier** [comment]
@benburkert sorry but I don't know about https configuration and i don't know what those env variables mean and what should be their values. Please explain if possible

**Comment by sylvaindethier** [comment]
@benburkert sorry again to bother you, i didn't understand i can have this token with the "Generate new tokens" button.
I'm trying right now.

**Comment by sylvaindethier** [comment]
@benburkert with those tokens, local https works even if my browsers (Firefox, Chrome) tell me the connexion is not secure. Is this normal ? Is this right ?
Thanks a lot for the support.

**Comment by sylvaindethier** [comment]
@geemus thanks the team for all the support, especially since i used the tool for a student project that didn't specify to work with https. I'm just trying it for the fun.

**Comment by benburkert** [comment]
> @benburkert with those tokens, local https works even if my browsers (Firefox, Chrome) tell me the connexion is not secure. Is this normal ? Is this right ?

i'm not sure the issue without more context, but at this point you should not be getting "connection is not secure" warnings in your browser. Mind [jumping in our discord](https://anchor.dev/discord)? That may be the fastest way to debug your issue.

**Comment by sylvaindethier** [comment]
@benburkert done ! I'm now on your discord.

**Comment by sylvaindethier** [comment]
We've been fixing the issue with the team.
For those who work in WSL, in order to not have security warning from the host OS (Windows 10/11) browsers, you have to:
- Install the Anchor CLI on the Windows system with PowerShell: `winget install Anchor.cli`
- Then run in the PowerShell: `anchor trust`

**Comment by geemus** [comment]
Thanks @sylvaindethier for updating and closing this out.

For a little extra context for us to remember and in case others run across this, since WSL is it's own VM the anchor command does it's work, but the changes are isolated inside that VM from the rest of the windows system. Other things running inside that VM should be able to find the certificates.

By running trust in powershell, it will install the certificates into the truststores outside the WSL VM, which would be needed for the browsers which run outside the VM. Having done that, it should mean that the same certificates should be available to command both inside and outside the VM.
