### ISSUE TITLE
Error: Post "https://api.anchor.dev/v0/cli/pat-tokens": non-json response received: "": %!w(<nil>)

### ISSUE THREAD

**Issue by yoricksenpai** [anchordotdev/cli#17]
**Are there any additional details you would like to share?**

---

**Command:** `lcl`
**Version:** `0.0.32 (darwin/amd64) Commit: 70e545ab44af45a58ac67a9a441eb2042cef9a8b BuildDate: 2024-05-06T19:02:26Z`
**Arguments:** `[]`
**Flags:** `[]`
**Stdout:**
```
# Signin to Anchor.dev `anchor auth signin`
    | Please sign up or sign in with your Anchor account.
    | 
    | Once authenticated, we can provision your personalized Anchor resources to
    | power HTTPS in your local development environment.
    - Copied your user code STMC-XTFS to your clipboard.
    - Opened https://anchor.dev/users/sign_in/cli?signup_src=lclhost in your browser
    * Signing in… ⠋
```

**Comment by geemus** [comment]
@yoricksenpai Thanks for the report. It appears this was related to some misbehavior at the infrastructure level that has resolved.

I'll work on some improvements to the error messages and handling related to this for the next release.

For now, the logs appear to show that you were able to retry and proceed, so I'll close this for now, but please let us know if you have further questions or feedback.
