### ISSUE TITLE
Error: request [741a03f0-3242-4920-b7d5-e8a608d3d117]: unexpected 404 status response: Server could not find Service.

### ISSUE THREAD

**Issue by NickThompsonDev** [anchordotdev/cli#32]
**Are there any additional details you would like to share?**

---

**Command:** `anchor lcl setup`
**Executable:** `C:\Program Files\Anchor CLI\anchor.exe`
**Version:** `0.0.38 (windows/amd64) Commit: 38a58bce9066abd76402b4acf560bfce5c03ec94 BuildDate: 2024-06-25T19:20:43Z`
**Arguments:** `[]`
**Flags:** `[]`
**Timestamp:** `2024-07-25T04:54:35.5182594Z`
**Stdout:**
```
# Setup lcl.host Application `anchor lcl setup`
    | We'll gather details from you and your system to customize setup instructions.
    - Scanned current directory.
    - Entered javascript application server type.
    - Entered TC application name.
    - Entered localhost.lcl.host domain for local application development.
    - Resolved localhost.lcl.host domain: success!
    | Now we'll provision Anchor.dev resources and HTTPS certificates for you.
    - Creating TC [localhost.lcl.host, localhost.localhost] javascript resources on Anchor.dev… ⠋
```

**Comment by NickThompsonDev** [comment]
duplicate i think

**Comment by NickThompsonDev** [comment]
it also doesnt like spaces in the name. i got it to work by just 1 word all lowercase for application name.

**Comment by geemus** [comment]
Thanks for following up and closing this. I believe spaces should also be fixed with the same patch mentioned on the other issue. So this should hopefully all be resolved once we get another release out.
