### ISSUE TITLE
Error: ext509: malformed Anchor Certificate Extension

### ISSUE THREAD

**Issue by sufyanazeem** [anchordotdev/cli#47]
**Are there any additional details you would like to share?**

---

**Command:** `anchor lcl`
**Executable:** `C:\Program Files\Anchor CLI\anchor.exe`
**Version:** `0.1.7 (windows/amd64) Commit: e75e108300982a9bef8d4cc465639591335fb658 BuildDate: 2024-11-12T19:34:37Z`
**Arguments:** `[]`
**Flags:** `[]`
**Timestamp:** `2024-11-16T19:57:52.2309958Z`
**Stdout:**
```
| Let's set up fast and totally free lcl.host HTTPS!
                                                                 
# Setup lcl.host HTTPS Local Development Environment `anchor lcl`
    | We'll set you up to use HTTPS locally in your browsers and other programs.
                                                                       
# Audit lcl.host HTTPS Local Development Environment `anchor lcl audit`
    | We'll compare your local development CA certificates from Anchor and your local trust stores.
    * Comparing local and expected CA certificates…⠋
```

**Comment by geemus** [comment]
@sufyanazeem Hey, sorry we didn't get back to you sooner. Are you still seeing this issue, or did it resolve somehow?

**Comment by sufyanazeem** [comment]
It's resolved now .
Thanks for asking

**Comment by geemus** [comment]
Great, glad to hear it. Just let us know if you have any further questions or feedback. Thanks.
