### ISSUE TITLE
Error in WSL 2.0 Ubuntu (brew) `Install Clang or run brew install gcc.` but I installed

### ISSUE THREAD

**Issue by neiesc** [anchordotdev/cli#6]
I have some erro running:
Error in WSL 2.0 Ubuntu (brew) `Install Clang or run `brew install gcc`.` but I installed

```
λ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
```
![image](https://github.com/anchordotdev/cli/assets/251643/3fe7041a-1b4d-4726-b043-0665636064c9)

**Comment by geemus** [comment]
Thanks for the report and sorry to hear you are running into this.

Could you try reinstalling gcc with `brew reinstall gcc`, as I've certainly seen cases where that fixed things (I think symlinks and/or path that had somehow gotten out of the expected state). As I haven't seen this before, I'm not at all certain that will help, but it shouldn't hurt anything and is hopefully easy to try as a starting point. Thanks!

**Comment by neiesc** [comment]
Oh, thx error fixed

**Comment by geemus** [comment]
Great, thanks for the update and just let us know if you have any further issues or feedback.
